# Generated by Django 2.0.5 on 2018-05-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=24, verbose_name='Titre de la question')),
                ('texte', models.TextField(null=True, verbose_name='Question')),
            ],
            options={
                'ordering': ['titre'],
                'verbose_name': 'question',
            },
        ),
    ]
