# Generated by Django 2.0.5 on 2018-05-21 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom utilisateur')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom utilisateur')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('photo', models.ImageField(upload_to='pic_folder')),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
    ]
