# Generated by Django 2.0.5 on 2018-05-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20180521_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'choix',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='QuestionReponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'question et réponse',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField(null=True, verbose_name='réponse')),
            ],
            options={
                'verbose_name': 'Réponse',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['titre'], 'verbose_name': 'Question'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AlterField(
            model_name='question',
            name='texte',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='questionreponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
        migrations.AddField(
            model_name='questionreponse',
            name='reponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Reponse'),
        ),
        migrations.AddField(
            model_name='choix',
            name='question_reponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.QuestionReponse'),
        ),
        migrations.AddField(
            model_name='choix',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
    ]
