# Generated by Django 2.0.5 on 2018-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20180521_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=100, null=True, verbose_name='Mail'),
        ),
    ]
