# Generated by Django 2.0.5 on 2018-07-25 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20180521_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interesse_par',
            field=models.CharField(default='tout', max_length=5, verbose_name='Interessé par'),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(default='indéterminé', max_length=5, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='user',
            name='tranche_age',
            field=models.IntegerField(default='20', verbose_name="Tranche d'âge"),
        ),
        migrations.AlterField(
            model_name='question',
            name='texte',
            field=models.TextField(null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(15)], verbose_name='Age'),
        ),
    ]
