# Generated by Django 2.0.5 on 2018-07-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20180725_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interesse_par',
            field=models.CharField(choices=[('F', 'Femme'), ('M', 'Homme'), ('T', 'Tout')], max_length=5, verbose_name='Interessé par '),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(choices=[('F', 'Femme'), ('M', 'Homme'), ('A', 'Ambigu')], max_length=5, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tranche_age',
            field=models.IntegerField(verbose_name="Tranche d'âge"),
        ),
    ]
