# Generated by Django 2.0.5 on 2018-07-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20180725_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tranche_age',
            field=models.IntegerField(choices=[('10', 10), ('20', 20), ('30', 30), ('40', 40), ('50', 50), ('60', 60), ('70', 70), ('80', 80), ('90', 90)], verbose_name="Tranche d'âge recherchée"),
        ),
    ]
