# Generated by Django 2.0.5 on 2018-07-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20180725_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tranche_age',
            field=models.CharField(choices=[('10', 'dizaine'), ('20', 'vingtaine'), ('30', 'trentaine'), ('40', 'quarantaine'), ('50', 'cinquantaine'), ('60', 'soixantaine'), ('70', 'soixante-dizaine'), ('80', 'quatre-vingtaine'), ('90', 'quatre-vingt-dizaine')], max_length=20, verbose_name="Tranche d'âge recherchée"),
        ),
    ]
