# Generated by Django 2.0.5 on 2018-07-25 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20180725_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDuJour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'question du jour',
            },
        ),
    ]
