# Generated by Django 2.0.5 on 2018-07-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_questiondujour'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=100, verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
    ]
