# Generated by Django 2.0.5 on 2018-07-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_auto_20180725_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choix',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
