# Generated by Django 2.0.5 on 2018-07-25 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_auto_20180725_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextra',
            name='tranche_age',
        ),
        migrations.AddField(
            model_name='userextra',
            name='age_max_voulu',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(15)], verbose_name='Age maximal voulu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userextra',
            name='age_min_voulu',
            field=models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(15)], verbose_name='Age minimal voulu'),
            preserve_default=False,
        ),
    ]
