# Generated by Django 2.0.5 on 2018-07-25 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_auto_20180725_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choix',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.UserExtra'),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='sexe',
            field=models.CharField(choices=[('F', 'Femme'), ('M', 'Homme')], max_length=5, verbose_name='Sexe'),
        ),
    ]
