# Generated by Django 2.0.7 on 2018-07-26 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_auto_20180726_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
