# Generated by Django 2.0.5 on 2018-07-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom utilisateur')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom utilisateur')),
                ('mdp', models.CharField(max_length=24, verbose_name='Mot de passe')),
                ('mail', models.CharField(max_length=100, verbose_name='Mail')),
                ('age', models.IntegerField(verbose_name='Age')),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
        ),
    ]
